build:
  version: "1.2"

accounts:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "John Doe - QA"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345